spring:
  application:
    name: Employee Management

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://aws-0-ap-south-1.pooler.supabase.com:6543/postgres
    hikari:
      maximum-pool-size: 10
      schema: hrms.management
    username: postgres.jjkvwelykzzjnvcpjmai
    password: 5aeyNCPqUhRJsnUG

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
